export default {
  productWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "calc(100vh - 50px)",
    pt: "20px",
    pb: "50px",
  },
  imgWrapper: {
    width: ["1", "1", "2/5", null, 450],
    textAlign: ["center", "center", "right"],
  },
  img: {
    width: "1",
    maxWidth: ["200px", null, "330px"],
    maxHeight: "360px",
    objectFit: "contain",
  },
  infoWrapper: {
    display: "flex",
    textAlign: ["center", "center", "left"],
    flexDirection: "column",
    width: ["1", "1", "3/5", null, 650],
    mt: ["20px", null, null, 0],
    pl: ["20px", 0, 0, "100px"],
    pr: ["20px", 0],
  },
  tag: {
    textTransform: "uppercase",
    color: "secondary",
    fontSize: [1, null, null, 2],
  },
  name: {
    variant: "heading",
    fontFamily: "body",
    fontWeight: "bold",
    color: "white",
    fontSize: [4, null, null, 6],
    mt: "5px",
    mb: ["15px", null, null, "25px"],
  },
  description: {
    maxWidth: "410px",
    width: "1",
    my: 0,
    mx: ["auto", null, "unset"],
    fontSize: [1, null, null, 2],
  },
  price: {
    color: "white",
    fontWeight: "bold",
    fontSize: 4,
    transform: [null, null, "translateX(-7px)"],
    mt: ["15px", null, null, "20px"],
    mb: "15px",
  },
  button: {
    variant: "button.primary",
    fontSize: 1,
    py: "13px",
    px: "32px",
    mx: ["auto", null, "unset"],
  },
}
