export default {
  card: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "flex-start",
    alignContent: "center",
    backgroundColor: "background.card",
    color: "inherit",
    textDecoration: "none",
    width: "100%",
    maxWidth: ["265px", null, "240px", null, null, "265px"],
    height: "273px",
    mx: "auto",
    padding: "32px 20px",
    borderColor: "gray",
    borderWidth: 3,
    borderStyle: "solid",
  },
  image: {
    maxHeight: "92px",
    mx: "auto",
  },
  title: {
    fontFamily: "body",
    fontWeight: "bold",
    textTransform: "uppercase",
    textAling: "left",
    marginTop: "37px",
    marginBottom: "10px",
  },
  description: {
    margin: 0,
    lineHeight: 1.2,
    fontSize: 1,
    paddingRight: "25px",
  },
  button: {
    position: "absolute",
    display: "block",
    variant: "button.primary",
    fontSize: 6,
    padding: 0,
    maxWidth: "44px",
    width: "100%",
    height: "44px",
    borderRadius: "22px",
    right: "7px",
    bottom: "7px",
  },
}
